# Generated by Django 5.0.6 on 2024-07-02 11:00
from django.db import migrations

def create_default_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('messaging', 'Profile')
    for user in User.objects.all():
        Profile.objects.get_or_create(user=user, defaults={'profile_photo': 'default.jpg', 'bio': 'This is a default bio.'})


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_profile_delete_customer'),
    ]

    operations = [
    ]
